version: 1.0.0
bmad:
  description: "BMAD methodology integration for structured development workflows"
  version: "1.0.0"
  resourceTypes:
    - tasks
    - templates
    - checklists
    - workflows
    - data
  commandPrefix: "*"
  loadOnDemand: true
  cacheEnabled: true
  cacheTimeoutMinutes: 60
