name: Development Branch CI

on:
  push:
    branches:
      - development

env:
  NODE_VERSION: '22'
  CI: true

concurrency:
  group: development-ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  # Minimal build check
  build-check:
    name: Build Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Success
        run: echo "✅ Development branch build successful"