name: Development Branch CI

on:
  push:
    branches:
      - development

env:
  NODE_VERSION: '22'
  CI: true

concurrency:
  group: development-ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  # Fast development validation
  development-validation:
    name: Development Build & Quality Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-dev-node-${{ env.NODE_VERSION }}-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-dev-node-${{ env.NODE_VERSION }}-
            ${{ runner.os }}-dev-node-

      - name: Install dependencies
        run: npm ci

      - name: Fast quality & build check
        run: |
          echo "🚀 Running development branch validation..."
          
          # Fast linting (fail fast for obvious issues)
          npm run lint
          
          # Type checking
          npm run type-check
          
          # Build project
          npm run build
          
          # Quick CLI test
          node bin/permamind.js --version
          
          echo "✅ Development branch validation successful"
          echo "🎯 Ready for PR creation or further development"