name: Package Validation

on:
  pull_request:
    paths:
      - 'package.json'
      - 'bin/**'
      - 'scripts/**'
      - 'templates/**'
      - '.github/workflows/npm-publish.yml'
      - '.github/workflows/package-validation.yml'
  workflow_dispatch:

jobs:
  validate-package-config:
    name: Validate Package Configuration
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build package
        run: npm run build

      - name: Validate package.json
        run: |
          echo "🔍 Validating package.json configuration..."
          
          # Check required fields for NPM publishing
          cat > validate-pkg.cjs << 'EOF'
          const pkg = require('./package.json');
          const required = ['name', 'version', 'description', 'author', 'license', 'repository', 'bin'];
          const missing = required.filter(field => !pkg[field]);
          if (missing.length > 0) {
            console.error('❌ Missing required fields:', missing);
            process.exit(1);
          }
          console.log('✅ All required package.json fields present');
          EOF
          node validate-pkg.cjs

      - name: Validate bin entries
        run: |
          echo "🔧 Validating bin entries..."
          
          cat > validate-bin.cjs << 'EOF'
          const pkg = require('./package.json');
          const fs = require('fs');
          
          if (!pkg.bin) {
            console.error('❌ No bin field in package.json');
            process.exit(1);
          }
          
          for (const [name, path] of Object.entries(pkg.bin)) {
            if (!fs.existsSync(path)) {
              console.error(`❌ Bin file not found: ${path}`);
              process.exit(1);
            }
            
            const stats = fs.statSync(path);
            if (!(stats.mode & 0o111)) {
              console.error(`❌ Bin file not executable: ${path}`);
              process.exit(1);
            }
            
            console.log(`✅ ${name}: ${path}`);
          }
          EOF
          node validate-bin.cjs

      - name: Validate files array
        run: |
          echo "📁 Validating files array..."
          
          cat > validate-files.cjs << 'EOF'
          const pkg = require('./package.json');
          const fs = require('fs');
          
          if (!pkg.files) {
            console.error('❌ No files field in package.json');
            process.exit(1);
          }
          
          const missingPaths = [];
          for (const filePattern of pkg.files) {
            const basePath = filePattern.replace('/**/*', '').replace('/*', '');
            if (basePath !== 'README.md' && basePath !== 'LICENSE' && !fs.existsSync(basePath)) {
              missingPaths.push(filePattern);
            }
          }
          
          if (missingPaths.length > 0) {
            console.error('❌ Missing paths in files array:', missingPaths);
            process.exit(1);
          }
          
          console.log('✅ All paths in files array exist');
          EOF
          node validate-files.cjs

  test-installation-simulation:
    name: Test Installation Simulation
    needs: validate-package-config
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        node-version: [20, 22]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build package
        run: npm run build

      - name: Create test package
        run: |
          echo "📦 Creating test package..."
          npm pack

      - name: Simulate global installation
        shell: bash
        run: |
          echo "🧪 Simulating global installation..."
          
          # Create a temporary directory for testing
          mkdir -p test-install
          cd test-install
          
          # Get the tarball name
          TARBALL=$(ls ../*.tgz | head -1)
          echo "Testing with tarball: $TARBALL"
          
          # Install the package
          npm install -g "$TARBALL"
          
          # Test that commands are available
          which permamind || echo "❌ permamind command not found in PATH"
          which permamind-setup || echo "❌ permamind-setup command not found in PATH"

      - name: Test CLI commands
        shell: bash
        run: |
          echo "🧪 Testing CLI commands..."
          
          # Test help command
          permamind --help
          
          # Test version command  
          permamind --version
          
          # Test setup command (should fail gracefully without user input)
          timeout 10 permamind-setup --help || echo "Setup command test completed"
          
          echo "✅ CLI commands working correctly"

  test-mcp-integration:
    name: Test MCP Integration
    needs: validate-package-config
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build package
        run: npm run build

      - name: Test MCP server startup
        run: |
          echo "🧪 Testing MCP server startup..."
          
          # Generate a test seed phrase
          export SEED_PHRASE="abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon about"
          
          # Test that server can start (timeout after 10 seconds)
          timeout 10 node dist/server.js || echo "Server startup test completed"
          
          echo "✅ MCP server startup test passed"

      - name: Test configuration generation
        run: |
          echo "🧪 Testing configuration generation..."
          
          # Test the configuration helper
          node scripts/configure.js list
          
          # Test environment variable generation
          node scripts/configure.js env "test-seed-phrase"
          
          echo "✅ Configuration generation test passed"

  security-scan:
    name: Security Scan
    needs: validate-package-config
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Install jq for JSON parsing
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Run security audit
        run: |
          echo "🔒 Running security audit..."
          # Note: Currently allowing node-forge vulnerabilities in arweave-mnemonic-keys dependency
          # These are required for Arweave wallet functionality and no fixes are available
          npm audit --audit-level high || {
            echo "⚠️ Security audit found vulnerabilities"
            echo "🔍 Checking if they are only in known dependencies..."
            
            # Check if vulnerabilities are only in acceptable dependencies
            npm audit --json > audit_output.json
            
            if [[ ! -s audit_output.json ]]; then
              echo "❌ Failed to generate audit output"
              exit 1
            fi
            
            # Use node.js to parse JSON instead of jq to avoid dependency issues
            node -e "
              const fs = require('fs');
              const audit = JSON.parse(fs.readFileSync('audit_output.json', 'utf8'));
              if (audit.vulnerabilities) {
                const packages = Object.keys(audit.vulnerabilities);
                packages.forEach(pkg => console.log(pkg));
              }
            " > vuln_packages.txt
            
            # Allow known vulnerable packages that are essential and have no fixes
            ALLOWED_VULNS="node-forge,crypto-key-composer,human-crypto-keys,arweave-mnemonic-keys,libp2p-crypto"
            
            if [[ -s vuln_packages.txt ]]; then
              while read -r package; do
                if ! echo "$ALLOWED_VULNS" | grep -q "$package"; then
                  echo "❌ Unexpected vulnerability in package: $package"
                  npm audit --audit-level moderate
                  exit 1
                fi
              done < vuln_packages.txt
              
              echo "✅ All vulnerabilities are in known/accepted dependencies"
              echo "🛡️ No new vulnerabilities found in application code"
            else
              echo "ℹ️ No vulnerabilities found in audit"
            fi
            
            # Clean up temporary files
            rm -f audit_output.json vuln_packages.txt
          }
          
      - name: Check for sensitive data
        run: |
          echo "🔍 Checking for sensitive data in package files..."
          
          # Check for actual secrets (not documentation or legitimate usage)
          FOUND_SECRETS=false
          
          # Look for actual secret patterns (not just words like "key" or "token")
          if grep -r "\(password\|secret\|key\|token\)\s*[:=]\s*['\"][^'\"]*['\"]" bin/ scripts/ templates/ --exclude-dir=node_modules --exclude="*.md" 2>/dev/null | \
             grep -v "SEED_PHRASE" | \
             grep -v "NPM_TOKEN" | \
             grep -v "GITHUB_TOKEN" | \
             grep -v "placeholder" | \
             grep -v "example" | \
             grep -v "your_" | \
             grep -v "<" | \
             grep -v "TODO" | \
             grep -v "FIXME"; then
            FOUND_SECRETS=true
          fi
          
          # Also check for common secret patterns
          if grep -r "['\"][a-zA-Z0-9]{20,}['\"]" bin/ scripts/ templates/ --exclude-dir=node_modules --exclude="*.md" 2>/dev/null | \
             grep -v "abandon abandon abandon" | \
             grep -v "test" | \
             grep -v "example" | \
             grep -v "placeholder" | \
             head -5; then
            echo "⚠️ Found potential long strings that could be secrets (review manually)"
          fi
          
          if [ "$FOUND_SECRETS" = true ]; then
            echo "❌ Potential sensitive data found in package files"
            exit 1
          fi
          
          echo "✅ No sensitive data found in package files"
          
  validate-readme:
    name: Validate README Instructions
    needs: validate-package-config
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check README installation instructions
        run: |
          echo "📖 Validating README installation instructions..."
          
          if ! grep -q "npm install -g permamind" README.md; then
            echo "❌ README missing npm install -g permamind instruction"
            exit 1
          fi
          
          if ! grep -q "permamind --setup" README.md; then
            echo "❌ README missing permamind --setup instruction"
            exit 1
          fi
          
          echo "✅ README contains proper installation instructions"

  final-validation:
    name: Final Package Validation
    needs: [validate-package-config, test-installation-simulation, test-mcp-integration, security-scan, validate-readme]
    runs-on: ubuntu-latest
    steps:
      - name: Validation summary
        run: |
          echo "🎉 All package validation tests passed!"
          echo "📦 Package is ready for NPM publishing"
          echo "✅ Configuration validated"
          echo "✅ Installation simulation successful"
          echo "✅ MCP integration tested"
          echo "✅ Security scan passed"
          echo "✅ README instructions validated"